# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: bg3mods-feed

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bg3mods-feed
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X=main.Version={{ .Version }}
      - -X=main.Commit={{ .Commit }}
      - -X=main.Date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin

upx:
  - ids: [bg3mods-feed]
    enabled: true
    compress: best
    lzma: true
    goos: [linux]

checksum:
  name_template: 'checksums.txt'

archives:
  - id: dist
    builds: [bg3mods-feed]
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: LICENSE
      - src: contrib/etc/config.yaml
        strip_parent: false
      - src: contrib/systemd/bg3mods-feed.service
        strip_parent: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: tinyzimmer
    name: bg3mods-feed

brews:
  - ids: [dist]
    homepage: https://github.com/tinyzimmer/bg3mods-feed
    description: A feed generator of mods for Baldur's Gate 3
    license: MIT
    url_template: "https://github.com/tinyzimmer/bg3mods-feed/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: auto
    directory: Formula
    repository:
      owner: tinyzimmer
      name: homebrew-bg3mods-feed
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Avi Zimmerman
      email: avi.zimmerman@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "bg3mods-feed"
    post_install: |
      etc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml"
    test: |
      system "#{bin}/bg3mods-feed --version"
    service: |
      run [bin/"bg3mods-feed", "--config", etc/"bg3mods-feed.conf.yaml"]
      keep_alive true
    caveats: |
      You can start the service with `brew services start bg3mods-feed`.
      The service will be available at http://localhost:8080/feed unless otherwise configured in #{etc}/bg3mods-feed.conf.yaml.

nfpms:
  - id: nfpm
    maintainer: Avi Zimmerman <avi.zimmerman@gmail.com>
    description: A feed generator of mods for Baldur's Gate 3
    homepage: https://github.com/tinyzimmer/bg3mods-feed
    license: MIT
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/bg3mods-feed/LICENSE
      - src: contrib/systemd/bg3mods-feed.service
        dst: /usr/lib/systemd/system/bg3mods-feed.service
      - src: contrib/etc/config.yaml
        dst: /etc/bg3mods-feed/config.yaml
    builds:
      - bg3mods-feed
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    archlinux:
      packager: Avi Zimmerman <avi.zimmerman@gmail.com>
      pkgbase: bg3mods-feed
