# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X=main.Version={{ .Version }}
      - -X=main.Commit={{ .Commit }}
      - -X=main.Date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: tinyzimmer
    name: bg3mods-feed

# brews:
#   - homepage: https://github.com/tinyzimmer/bg3mods-feed
#     description: "A feed generator of mods for Baldur's Gate 3"
#     license: MIT
#     url_template: "https://github.com/tinyzimmer/bg3mods-feed/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     skip_upload: auto
#     repository:
#       owner: tinyzimmer
#       name: homebrew-bg3mods-feed
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     commit_author:
#       name: Avi Zimmerman
#       email: avi.zimmerman@gmail.com
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     install: |
#       bin.install "bg3mods-feed"
#     test: |
#       system "#{bin}/bg3mods-feed --version"
#     service: |
#       run "#{bin}/bg3mods-feed"
#       keep_alive true
#       sockets "tcp://127.0.0.1:8080"
#     caveats: |
#       You can start the service with `brew services start bg3mods-feed`
